[package]
name = "file_types"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# Internal crates
structs = { path = "../structs" }

# External crates
csv.workspace = true
serde_json.workspace = true
dotenv.workspace = true
dotenvy.workspace = true